const express = require("express")
const cors = require("cors")
const {connect} = require("./confiq/db")
require("dotenv").config({path:".env"})
connect()
const app = express()
app.use(express.json())
app.use(express.static("public"))
app.use(cors())
app.use("/user", require("./routes/userRoute"))
app.use("/doc", require("./routes/docRoute"))
app.listen(process.env.PORT, console.log("http://localhost:5000"))